route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-alert'        # main receiver
  routes:
    - receiver: 'web.hook'       # secondary route example

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'fidelis@gmail.com'             # where you want to receive alerts
        from: 'fidelis@gmail.com'           # sender
        smarthost: 'smtp.gmail.com:587'    # Gmail SMTP server
        auth_username: 'fidelis@gmail.com'  # your Gmail login
        auth_identity: 'fidelis@gmail.com'  # same as username
        auth_password: '*******'       # Gmail App Password (NOT your Gmail password)

  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'       # example webhook

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']