groups:
  - name: ExampleAlerts
    rules:
      - alert: HighCPUUsage
        expr: process_cpu_seconds_total > 0.5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected"
          description: "The CPU usage is above 50% for more than 1 minute."
